### ISSUE TITLE
maxThickness is incorrect (causing artifacts)

### ISSUE THREAD

**Issue by znakeeye** [Blatko1/MSDF-showcase#1]
Awesome `msdfgen` samples. Thanks a lot!

[outlining.frag](https://github.com/Blatko1/awesome-msdf/blob/9d3486408d19c72991945d499b745928fc5f465e/shaders/outlining.frag#L25C7-L25C20) contains a bug where the thickness becomes greater than `0.3`, causing vertical lines to appear.

The comment seems to indicate that the thickness should be in the range of -0.3 to 0.3, so I guess the artifact is expected. You might want to fix the code though, since `maxThickness` is in fact set to **0.6**.
```c
float thickness = -0.2; // Range: -0.3 < thickness < 0.3
float maxThickness = 0.4 - thickness;
```

![image](https://github.com/Blatko1/awesome-msdf/assets/958469/5dba313b-0278-4d15-a73a-4c2ce923591d)

**Comment by Blatko1** [comment]
I appreciate that this crate helped you, and thank you for contributing!

Yes, the `thickness` **must not** be over `0.5` (or below `-0.5`) if you want to avoid artefacts, and now, after further inspection, I see some confusing and unclear parts in the code and some invalid ranges. I'll make the code more straightforward and easier to read in the following few commits.
